USE [master]
GO

/****** Object:  Database [IFML]    Script Date: 10/03/2019 23:38:12 ******/
CREATE DATABASE [IFML] ON  PRIMARY 
( NAME = N'IFML', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\IFML.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IFML_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\IFML_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [IFML] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IFML].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IFML] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IFML] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IFML] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IFML] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IFML] SET ARITHABORT OFF 
GO

ALTER DATABASE [IFML] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IFML] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [IFML] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IFML] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IFML] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IFML] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IFML] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IFML] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IFML] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IFML] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IFML] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IFML] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IFML] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IFML] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IFML] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IFML] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IFML] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IFML] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IFML] SET  READ_WRITE 
GO

ALTER DATABASE [IFML] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IFML] SET  MULTI_USER 
GO

ALTER DATABASE [IFML] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IFML] SET DB_CHAINING OFF 
GO

